version: "3.9"
services:
  postgres:
    image: postgres:16
    container_name: newpostgres_container
    environment:
      POSTGRES_DB: chatapp
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports: 
      - '5432:5432'
    volumes:
      - app-db:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql


  app:
    #build:
    #  context: .
    #  dockerfile: Dockerfile
    image: newchat_app:v4
    container_name: new_chatapp_containter
    depends_on:
      - postgres
    environment:
      #DATABASE_URL: postgres://postgres:1234@postgres:5432/chatapp
      DATABASE_NAME: chatapp
      DATABASE_USER: postgres
      DATABASE_PASSWORD: 1234
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
    ports:
      - '3000:3000'
        
volumes:
  app-db: