version: "3.9"
services:
  postgres:
    image: postgres:16
    container_name: db_postgres_container
    environment:
      POSTGRES_DB: chatapp
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports: 
      - '5432:5432'
    volumes:
      - app-db:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql   # db tables init


  app:
    build:
     context: .
     dockerfile: Dockerfile
    container_name: chatapp_containter
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://postgres:1234@postgres:5432/chatapp  # contains all information db needs
    ports:
      - '3000:3000'
        
volumes:
  app-db: